[[LibMPDec]]
arch = "aarch64"
git-tree-sha1 = "add916cdc1ddbf86507bbbc5b3f3d1f556568341"
os = "macos"

    [[LibMPDec.download]]
    sha256 = "2a2638790967aec446065af00f57f116ba84a04c55cb787f9402d7af62f3484f"
    url = "https://github.com/JuliaBinaryWrappers/LibMPDec_jll.jl/releases/download/LibMPDec-v2.5.2+0/LibMPDec.v2.5.2.aarch64-apple-darwin.tar.gz"
[[LibMPDec]]
arch = "aarch64"
git-tree-sha1 = "c1114cb470d9cd0286f9f5d9822a096535461993"
libc = "glibc"
os = "linux"

    [[LibMPDec.download]]
    sha256 = "d4956b72884e49e1f7bcb69eb9cda27493cc359a8d099eaf5d468b65cfbd0d0f"
    url = "https://github.com/JuliaBinaryWrappers/LibMPDec_jll.jl/releases/download/LibMPDec-v2.5.2+0/LibMPDec.v2.5.2.aarch64-linux-gnu.tar.gz"
[[LibMPDec]]
arch = "aarch64"
git-tree-sha1 = "570932c1809478e548933dd51bbacd144e023f8c"
libc = "musl"
os = "linux"

    [[LibMPDec.download]]
    sha256 = "9f36f72fb8afec8f4ae7b5e2210992fe89db1b896d8884363362fdbc4d04c35a"
    url = "https://github.com/JuliaBinaryWrappers/LibMPDec_jll.jl/releases/download/LibMPDec-v2.5.2+0/LibMPDec.v2.5.2.aarch64-linux-musl.tar.gz"
[[LibMPDec]]
arch = "aarch64"
git-tree-sha1 = "03abe08ae8fdb5c563b5a28bbeadaa678e91c208"
os = "freebsd"

    [[LibMPDec.download]]
    sha256 = "610b0a3edb6801d79e2d018b3d3c2b823021a6042a0cca9fa5245fd6b55a5d38"
    url = "https://github.com/JuliaBinaryWrappers/LibMPDec_jll.jl/releases/download/LibMPDec-v2.5.2+0/LibMPDec.v2.5.2.aarch64-unknown-freebsd.tar.gz"
[[LibMPDec]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a0feeb47cdbb26bf851907c5d83e42f0e075c689"
libc = "glibc"
os = "linux"

    [[LibMPDec.download]]
    sha256 = "096152b01bd5b7d0fd18b59db6409f1384a154f355d08d129930008c04ac16d4"
    url = "https://github.com/JuliaBinaryWrappers/LibMPDec_jll.jl/releases/download/LibMPDec-v2.5.2+0/LibMPDec.v2.5.2.armv6l-linux-gnueabihf.tar.gz"
[[LibMPDec]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "65f4cdaf5787d3ee81c91b1f657eb3c48357c623"
libc = "musl"
os = "linux"

    [[LibMPDec.download]]
    sha256 = "fb0564f19d86f543ef8be8dac1127154c6e5993172d72be40b14ec674774cf3b"
    url = "https://github.com/JuliaBinaryWrappers/LibMPDec_jll.jl/releases/download/LibMPDec-v2.5.2+0/LibMPDec.v2.5.2.armv6l-linux-musleabihf.tar.gz"
[[LibMPDec]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d3c03af35a2e9c77f04bc7d764c6f8719ec50ed9"
libc = "glibc"
os = "linux"

    [[LibMPDec.download]]
    sha256 = "61bd63a6fa56657cc15d0f12cad3948c1f77585d1491e2f62661d71bec6709c0"
    url = "https://github.com/JuliaBinaryWrappers/LibMPDec_jll.jl/releases/download/LibMPDec-v2.5.2+0/LibMPDec.v2.5.2.armv7l-linux-gnueabihf.tar.gz"
[[LibMPDec]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4611ed128f4d832cc2960e939a9ea46da44e3f33"
libc = "musl"
os = "linux"

    [[LibMPDec.download]]
    sha256 = "3a12add8f231db1e922d33641c73285e419750fcb94ddb30d1714a48d8402f7e"
    url = "https://github.com/JuliaBinaryWrappers/LibMPDec_jll.jl/releases/download/LibMPDec-v2.5.2+0/LibMPDec.v2.5.2.armv7l-linux-musleabihf.tar.gz"
[[LibMPDec]]
arch = "i686"
git-tree-sha1 = "0c3a53eb73ddafb149f10d2a35ba467206841ac0"
libc = "glibc"
os = "linux"

    [[LibMPDec.download]]
    sha256 = "4d82459585b6c20b6edd57995826db80f620554f05e227ca8d7beaa6d9e9a0c7"
    url = "https://github.com/JuliaBinaryWrappers/LibMPDec_jll.jl/releases/download/LibMPDec-v2.5.2+0/LibMPDec.v2.5.2.i686-linux-gnu.tar.gz"
[[LibMPDec]]
arch = "i686"
git-tree-sha1 = "9b4e559f6f8e5f9d87c5b1c55822e0fbd82f5965"
libc = "musl"
os = "linux"

    [[LibMPDec.download]]
    sha256 = "f03a676eeca0f9f3709cb15ea4e004b4b40b5149ef8edf7a6958a06efd4149a5"
    url = "https://github.com/JuliaBinaryWrappers/LibMPDec_jll.jl/releases/download/LibMPDec-v2.5.2+0/LibMPDec.v2.5.2.i686-linux-musl.tar.gz"
[[LibMPDec]]
arch = "i686"
git-tree-sha1 = "f52dbca4c38e0337c85b13bf346ee29f206275ef"
os = "windows"

    [[LibMPDec.download]]
    sha256 = "4cd280f69c48b9ff74ae193c817b8ec2839fe6ad44c23d406a7b93b0977623b6"
    url = "https://github.com/JuliaBinaryWrappers/LibMPDec_jll.jl/releases/download/LibMPDec-v2.5.2+0/LibMPDec.v2.5.2.i686-w64-mingw32.tar.gz"
[[LibMPDec]]
arch = "powerpc64le"
git-tree-sha1 = "2c45cf1728476aed07128a0cae525febf353e2f1"
libc = "glibc"
os = "linux"

    [[LibMPDec.download]]
    sha256 = "5ff26f97eb53e53e3f756660979c6c7ec5f9a66f841639a9320f47cb08d75741"
    url = "https://github.com/JuliaBinaryWrappers/LibMPDec_jll.jl/releases/download/LibMPDec-v2.5.2+0/LibMPDec.v2.5.2.powerpc64le-linux-gnu.tar.gz"
[[LibMPDec]]
arch = "riscv64"
git-tree-sha1 = "fde46132ac480b778e0535e3e4b6f590759cba35"
libc = "glibc"
os = "linux"

    [[LibMPDec.download]]
    sha256 = "357e617dd3f33f582e1bb36176b0ab9ad197db3b55e68eebc2ba8af2e4873e4b"
    url = "https://github.com/JuliaBinaryWrappers/LibMPDec_jll.jl/releases/download/LibMPDec-v2.5.2+0/LibMPDec.v2.5.2.riscv64-linux-gnu.tar.gz"
[[LibMPDec]]
arch = "x86_64"
git-tree-sha1 = "7faf8309a8035aad3b568313802c2b44f67a196e"
os = "macos"

    [[LibMPDec.download]]
    sha256 = "91cbb8b1e49fb7785cda1fb091171fd57ff120ac15d39f0ec2e9f7a4e1b78344"
    url = "https://github.com/JuliaBinaryWrappers/LibMPDec_jll.jl/releases/download/LibMPDec-v2.5.2+0/LibMPDec.v2.5.2.x86_64-apple-darwin.tar.gz"
[[LibMPDec]]
arch = "x86_64"
git-tree-sha1 = "8535f1d9e1f47e434efe6f10c94f8069e1b2c468"
libc = "glibc"
os = "linux"

    [[LibMPDec.download]]
    sha256 = "96c9f2a0d8864835d26810da7bb9500dc5b5607e79d8a503967dc6e406e93776"
    url = "https://github.com/JuliaBinaryWrappers/LibMPDec_jll.jl/releases/download/LibMPDec-v2.5.2+0/LibMPDec.v2.5.2.x86_64-linux-gnu.tar.gz"
[[LibMPDec]]
arch = "x86_64"
git-tree-sha1 = "4fd649d008d1a28773c76de9dce16e0fc64dcb4a"
libc = "musl"
os = "linux"

    [[LibMPDec.download]]
    sha256 = "73023c2a6813029d6ff8af24e5cc21d005ab1aaf7e41746e3e17ffd1adf35c29"
    url = "https://github.com/JuliaBinaryWrappers/LibMPDec_jll.jl/releases/download/LibMPDec-v2.5.2+0/LibMPDec.v2.5.2.x86_64-linux-musl.tar.gz"
[[LibMPDec]]
arch = "x86_64"
git-tree-sha1 = "8aa2072982281db4dbeacaef4dc593dff3099476"
os = "freebsd"

    [[LibMPDec.download]]
    sha256 = "005d76b6e32ee52e1d68d91374a017d1a448c998da902af2413e81b6ebc97fdc"
    url = "https://github.com/JuliaBinaryWrappers/LibMPDec_jll.jl/releases/download/LibMPDec-v2.5.2+0/LibMPDec.v2.5.2.x86_64-unknown-freebsd.tar.gz"
[[LibMPDec]]
arch = "x86_64"
git-tree-sha1 = "5587949dea2cba22335c960b85af02ecaa8d8539"
os = "windows"

    [[LibMPDec.download]]
    sha256 = "e78c8f5f85e79e8672f74283d7ab2a46a30033590ba112ac1cee95ec6d254dc8"
    url = "https://github.com/JuliaBinaryWrappers/LibMPDec_jll.jl/releases/download/LibMPDec-v2.5.2+0/LibMPDec.v2.5.2.x86_64-w64-mingw32.tar.gz"
