# Autogenerated wrapper script for LibMPDec_jll for aarch64-apple-darwin
export libmpdec

JLLWrappers.@generate_wrapper_header("LibMPDec")
JLLWrappers.@declare_library_product(libmpdec, "@rpath/libmpdec.3.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmpdec,
        "lib/libmpdec.2.5.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
