# Autogenerated wrapper script for LibMPDec_jll for x86_64-w64-mingw32
export libmpdec

JLLWrappers.@generate_wrapper_header("LibMPDec")
JLLWrappers.@declare_library_product(libmpdec, "libmpdec-2.5.1.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmpdec,
        "bin\\libmpdec-2.5.1.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
